#SPDX-License-Identifier: MIT-0
---
# tasks file for install_package

- name: Install package on Debian-based systems
  apt:
    name: "{{ package }}"
    state: present
  when: ansible_os_family == "Debian"

- name: Install package on RedHat-based systems
  yum:
    name: "{{ package }}"
    state: present
  when: ansible_os_family == "RedHat"

- name: Install package on macOS systems
  community.general.homebrew:
    name: "{{ package }}"
    state: present
  become: false
  when: ansible_os_family == "Darwin"
